trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    itemPattern: 'public/*'
    downloadPath: '$(System.ArtifactsDirectory)'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
