# Header
menu:
  Home: /
  Archives: /archives
  Dejan: /Dejan-Fajfar
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-17432459-2
favicon: css/images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: